export {default as Header1} from './header1'
export {default as Header2} from './header2'
export {default as Header3} from './header3'
export {default as Header4} from './header4'
export {default as Header5} from './header5'
export {default as Header6 }from './header6'